nss/account_app/urls.py
###Last modified by Martín Helmut on Oct 20,2018
from django.urls import path, include
from account_app import views
from project_app.urls import projects_patterns
from .views import ProfileAccountUpdate

app_name = 'account_app'
urlpatterns=[

    #path('', views.see_project, name = 'see_project'),
    path('registrar/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('profile/', ProfileAccountUpdate.as_view(), name="profile"),

    #path('create_profile/',views.form_profile, name='form_profile'),

    # path('my_projects/', MyProjectsView.as_view(), name='my_projects'),
    # path('projects/',include(projects_patterns)),
]

nss/nss/urls.py
#Last modified by César Buenfil on Oct 19,2018

"""nss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an imlport:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from account_app import views
from django.conf import settings
from django.conf.urls.static import static
from project_app.urls import projects_patterns
from profiles_app.urls import profiles_patterns
from messages_app.urls import  messages_app_patterns
#SOCIAL AUTH
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
    path('',views.IndexView.as_view(),name='index'), #Despliega lo de la funcion index en appOne/views.py/def index
    path('user/', include('account_app.urls')),
    path('search/', include('search_app.urls')),

    #path('crearProyecto/',include('appOne.urls')),
    #path('createProyect/',views.form_name_view,name='form_name'),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    #path('create_profile/',views.form_profile, name='form_profile'),
    path('project_app/',include(projects_patterns)),
    path('', include('django.contrib.auth.urls')), # EMAIL RESET
    path('oauth/', include('social_django.urls', namespace="social")),
    path('profiles_app/', include(profiles_patterns)),
    path('messages_app/', include(messages_app_patterns)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#models
#Help us incorporate a database into a django project

nss/project_app/urls.py
from django.urls import path
from .views import ProjectsListView,GroupCreate,DataRepGoogle,ApplicationsDetailView,delete,accept,button_text, change_user_project_status ,ProjectDetailView, ProjectCreate, ProjectUpdate, ProjectDelete, DataRep, ProjectRolCreate
from project_app import views
app_name="project_app"
projects_patterns = ([
    path('p/', ProjectsListView.as_view(), name='projects'),
    path('<int:pk>/a/', ApplicationsDetailView.as_view(), name='applications'),
    path('<int:pk>/<slug:slug>/', ProjectDetailView.as_view(), name='project'),
    path('ajax/change_user_project_status/', views.change_user_project_status, name='change_user_project_status'),
    path('ajax/button_text/', views.button_text, name='button_text'),
    path('ajax/accept/', views.accept, name='accept'),
    path('ajax/delete/', views.delete, name='delete'),
    path('create/', ProjectCreate.as_view(), name='create'),
    path('createGroup/', GroupCreate.as_view(), name='create_group'),
    path('DataRep/', views.DataRep, name='DataRep'),
    path('DataRepGoogle/', views.DataRepGoogle, name='DataRepGoogle'),
    path('update/<int:pk>/', ProjectUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDelete.as_view(), name='delete'),
    path('createRolProyecto/<int:pk>/<slug:slug>/', ProjectRolCreate.as_view(), name = 'form_rol_project'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
    path('like/',views.like_post, name ="like_post"),

], 'project_app')

nss/search_app/urls.py
###Last modified by Martín Helmut on Oct 20,2018
from django.urls import path, include
from search_app import views
from project_app.urls import projects_patterns

app_name = 'search_app'
urlpatterns=[
    path('',views.SearchView.as_view(),name='search'),
]

nss/project/models.py
from django.db import models
from ckeditor.fields import RichTextField

#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title

class Project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')
    pro_description = models.TextField(max_length=800,default='')
    pro_video = EmbedVideoField() # models.URLField()
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_location = models.ForeignKey('location', on_delete=models.PROTECT,default='')
    pro_roles = models.ManyToManyField('rolInfo') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields
    
    def __str__(self):
        return self.pro_name

nss/project_app/models.py
"""
Last modified: ANgélica Güemes
date: November 8
Time: 8:40
"""
from django.db import models
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title

class category(models.Model):
     category = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.category

class subcategory(models.Model):
     subcategory = models.CharField(primary_key=True,max_length = 50, unique = True, default='')
     category = models.ForeignKey('category', on_delete=models.PROTECT,default='')

     def __str__(self):
        return self.subcategory

class state(models.Model): #estado
     state = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.state

class city(models.Model): #ciudad
     city = models.CharField(primary_key=True,max_length = 50, unique = True, default='')
     state = models.ForeignKey('state', on_delete=models.PROTECT,default='')
     def __str__(self):
        return self.city

class rolInfo(models.Model):#info del rol
    rol_name =  models.CharField(max_length = 150,  default='')
    rol_name_other=models.CharField(max_length = 150,  default='', blank=True)
    rol_due_date = models.DateField()
    rol_amount = models.PositiveIntegerField(default=1)
    rol_description = models.TextField(max_length=800, default='')
    rol_city = models.ForeignKey('city', on_delete=models.PROTECT,default='')
    rol_state = models.ForeignKey('state', on_delete=models.PROTECT,default='')


    def __str__(self):
        return self.rol_name

class project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')
    #Import RichTextField
    pro_description = RichTextField(verbose_name="Descripción", max_length=5000)
    pro_video = EmbedVideoField() # models.URLField()
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_img = models.ImageField(default='', upload_to='pro_img', blank=True)# null=true se pone null en la base de datos como entrada
    pro_group = models.BooleanField()
    likes = models.ManyToManyField(User,related_name="likes",blank=True)
    pro_save_times = models.PositiveIntegerField(default=0)

    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_subcategory = models.ForeignKey('subcategory', on_delete=models.PROTECT,default='')

    pro_city = models.ForeignKey('city', on_delete=models.PROTECT,default='')
    pro_state = models.ForeignKey('state', on_delete=models.PROTECT,default='')

    pro_roles = models.ManyToManyField('rolInfo', through='project_rol') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields

    pro_user = models.ForeignKey(User, on_delete=models.CASCADE, default="", blank=True, null=True)

    class Meta:
            verbose_name = "project_app"
            verbose_name_plural = "project_app"
            ordering = ['order','pro_name']

    def __str__(self):
        return self.pro_name

    def total_likes(self):
        return self.likes.count()



class projectImg(models.Model):#Ya no se usa
    pro_img = models.ImageField(default='', upload_to='pro_img', blank=True)
    pro = models.ForeignKey('project', on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.pro_img)

class project_rol(models.Model):#Tabla NN
    id= models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    pro = models.ForeignKey('project', related_name='project', on_delete=models.CASCADE,default='')
    rol= models.ForeignKey('rolInfo', related_name='rolInfo', on_delete=models.CASCADE,default='')
    def __str__(self):
        return str(self.rol)

class user_project(models.Model):
    up_project = models.ForeignKey('project', related_name='up_project', on_delete=models.CASCADE,default='')
    up_user = models.ForeignKey(User, on_delete=models.CASCADE, default="", blank=True, null=True)
    up_rolInfo =  models.ForeignKey('rolInfo', related_name='up_rolInfo', on_delete=models.CASCADE,default='')
    up_status = models.ForeignKey('status', related_name='upstatus', on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.up_project)

class status(models.Model):
    status= models.CharField(primary_key=True,max_length = 50, unique = True, default='')
    status_text= models.CharField(max_length=40,default='')
    def __str__(self):
        return str(self.status)

nss/search_app/models.py
from django.db import models

# Create your models here.

nss/search_app/views.py
### Last modified by César Buenfil on Oct 14,2018

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail
from django.urls import reverse
from urllib.parse import urlencode
from project_app.models import project, projectImg, project, rolInfo, state, city, category, subcategory
from project_app import models
from django.db.models import Q
from functools import reduce
from django.views import generic
from braces.views import SelectRelatedMixin
import operator
#login
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

#Class Based views
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView, UpdateView,
                                DeleteView)
# Create your views here.

class SearchView(SelectRelatedMixin, generic.ListView):
    template_name = 'search_app/search.html'
    context_object_name = 'projects'
    model = models.project
    select_related = ("pro_category","pro_subcategory", "pro_state", "pro_city")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['state'] = state.objects.all()
        context['category'] = category.objects.all()
        return context

    def get_queryset(self):
        result = super(ListView, self).get_queryset()

        if self.request.GET.get('q'):
            query = self.request.GET.get('q')
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(pro_name__icontains=q) for q in query_list))
            )
        if self.request.GET.get('id_pro_category'):
            id_pro_category = self.request.GET.get('id_pro_category')
            query_list = id_pro_category.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(pro_category=id_pro_category) for id_pro_category in query_list))
            )
        if self.request.GET.get('id_pro_subcategory'):
            id_pro_subcategory = self.request.GET.get('id_pro_subcategory')
            query_list = id_pro_subcategory.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(pro_subcategory=id_pro_subcategory) for id_pro_subcategory in query_list))
            )
        if self.request.GET.get('id_pro_state'):
            id_pro_state = self.request.GET.get('id_pro_state')
            query_list = id_pro_state.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(pro_state=id_pro_state) for id_pro_state in query_list))
            )
        if self.request.GET.get('id_pro_city'):
            id_pro_city = self.request.GET.get('id_pro_city')
            query_list = id_pro_city.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(pro_city=id_pro_city) for id_pro_city in query_list))
            )

        if self.request.GET.get('id_pro_group') == 'grupos':
            id_pro_group = self.request.GET.get('id_pro_group')
            result = result.filter(pro_group=True)

        if self.request.GET.get('id_pro_group') == 'proyectos':
            id_pro_project = self.request.GET.get('id_pro_group')
            result = result.filter(pro_group=False)

        return result

def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)

nss/search_app/templates/search_app/base_search_app.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="es">
        <head>
            <meta charset="utf-8">
            {% block meta_block %}

            {% endblock %}
            <meta name="viewport" content="width=device-width, initial-scale=1">
             <title>{% block title %}{% endblock %}</title>
            <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
            <link rel="stylesheet" href="{% static "css/semantic/out/semantic.min.css" %}">

            <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
            <script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
            <link rel="stylesheet" href="{% static "css/extras/processes.css" %}">
            {% block processes_block %}

            {% endblock %}
            <link rel ="stylesheet" href="{% static "css/styles.css" %}">
            <link href="{% static "css/custom_ckeditor.css" %}" rel="stylesheet">
            <link rel ="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
            <script type ="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
            <script type ="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
            <script type ="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
        </head>
    <body class="bg-gray">
        <!-- Static navbar -->
        <div class="ui borderless menu bg-prim stackable shadow number1">
            <div class="ui container">
                <div class="header item">
                    <a href="{% url 'index' %}" class="item text-white"><img class="logo" src="{% static "img/Teem.png" %}"></a>
                </div>
              <!--  <a class="item" href="{% url 'project_app:DataRep' %}"><i class="chart bar alternate icon"></i>Data representation</a>-->
                {% if user.is_authenticated %}
                <a class="item right text-white" href="{% url 'profiles_app:list' %}"><i class="users icon"></i> {%trans "Ver Perfiles" %}</a>
                <div class="ui simple dropdown item text-white">
                  <i class="edit icon text-white"></i>Crear
                  <i class="dropdown icon text-white"></i>
                  <div class="menu">
                       <a class="item" href="{% url 'project_app:create' %}"><i class="pencil alternate icon"></i>{% trans "Crear proyecto" %}</a>
                       <a class="item" href="{% url 'project_app:create_group' %}"><i class="pencil alternate icon"></i>{%trans "Crear Grupo" %}</a>
                  </div>
                </div>

                <a class="item text-white" href="{% url 'project_app:projects' %}"><i class="folder open icon"></i>{% trans "Mis Creaciones" %}</a>
                <div class="ui simple dropdown item text-white">
                  <i class="user icon text-white"></i>{{ user.username }}
                  <i class="dropdown icon text-white"></i>
                  <div class="menu">
                    <a class="item text-white" href="{% url 'messages_app:list' %}"><i class="comment alternate outline icon"></i>Mensaje directo</a>
                    <a class="item text-white" href="{% url 'profiles_app:detail' user %}"><i class="user circle outline icon"></i>{%trans "Ver Perfil" %}</a>
                    <a class="item text-white" href="{% url 'account_app:profile' %}"><i class="edit outline icon"></i>{% trans "Editar Perfil "%}</a>
                    <a class="item text-white" href="{% url 'logout' %}"><i class="power off icon"></i>{%trans "Salir"%}</a>
                  </div>
                </div>
              </div>
                {% else %}
                <a class="item ui right floated text-white" href="{% url 'account_app:user_login' %}">{%trans "Iniciar Sesion"%}</a>
                <div class="item">
                  <a class="ui button teal" href="{% url 'account_app:register' %}">{%trans "Registrarse "%}</a>
                </div>
                {% endif %}
            </div>
        </div>

        {% block body_block %}
        <!-- Other Htmls go here -->
        {% endblock %}

    </body>
    {% block js_block %}


    {% endblock %}
    <footer>
      <div class="ui vertical footer segment">
        <div class="ui center aligned container">
          <div class="ui section divider "></div>
          <div class="ui horizontal small divided link list ">
            <a class="item" href="#">{%trans "Mapa del Sitio"%}</a>
            <a class="item" href="#">{%trans "Contactanos"%}</a>
            <a class="item" href="#">{%trans "Terminos y Condiciones"%}</a>
            <a class="item" href="#">{%trans "Politica de Privacidad"%}</a>
            <a class="item"><form action="{%url 'set_language'%}" method="post">{%csrf_token%}
            <input type="hidden" name="text" value="{{redirect_to}}">
            <select name="language" id="">
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <option value="{{language.code}}" {% if language.code == LANGUAGE_CODE %} selected {%endif %}>
                  {{language.name_local}}({{language.code}})
                </option>
              {%endfor%}
            </select>
            <input type="submit" value="{%trans 'Ir' %}">
          </form></a>
          </div>
        </div>
      </div>
    </footer>
    <script type="text/javascript">
    $('.ui.accordion').accordion();
    </script>

</html>

nss/search_app/templates/search_app/project_list.html
{% for project in projects %}
{{project}}


<div class="ui container mb-4">
  <div class="ui link cards">
  {% for project in projects|dictsort:"id" reversed %}
      <div class="card">
        <div class="image">
          {% if project.pro_img %}
            <img src="../media/{{project.pro_img}}">
          {% else %}
            <img src="https://semantic-ui.com/images/wireframe/image.png">
          {% endif %}

        </div>
        <div class="content">
          <div class="header">{{project.pro_name}}</div>
          <div class="meta">
            <a>{{project.pro_category}}</a>
          </div>
          <div class="description">
            {{project.pro_description |safe}}
          </div>
        </div>
        <div class="extra content">
          <span class="right floated">
            Joined in 2013
          </span>
          <span>
            <i class="user icon"></i>
            <div class="row mt-3">
              <div class="col-md-9 mx-auto">
                <div>
                  {# <p>{{project.pro_description|striptags|safe|truncatechars:"200"}}</p> #}
                  <p><a href="{% url 'project_app:project' project.id project.pro_name|slugify %}">Leer más</a></p>

                  {% if request.user == project.pro_user %}
                  <a href="{% url 'project_app:applications' project.id %}">Ver solicitudes</a>
                | <a href="{% url 'project_app:update' project.id %}">Editar</a>
                | <a href="{% url 'project_app:delete' project.id %}">Borrar</a>
                    {% endif %}

                    <script type="text/javascript">
                    console.log("{% url 'project_app:project' project.id project.pro_name|slugify %}");

                    </script>

                </div>
              </div>
            </div>
          </span>
        </div>
      </div>

  {% endfor %}
  </div>
</div>
{% endfor %}

nss/search_app/templates/search_app/search.html
<!DOCTYPE html>
{% extends "search_app/base_search_app.html" %}
{% load staticfiles %}
{% block processes_block %}
<script type ="text/javascript" src="{% static "js/extras/processes.js" %}"></script>  <!--Este link hace que no jale el datepicker de create_project.html-->
{% endblock %}
{% block title %}Teem: Buscar{% endblock %}
{% block body_block %}
<div class="container">
  <form id="projectForm" action='{% url 'search_app:search' %}' data-cities-url="{% url 'project_app:ajax_load_cities' %}" data-subcategories-url="{% url 'project_app:ajax_load_subcategories' %}">
    <div class="ui five column doubling stackable grid container">
      <div class="column">
        <div class="ui form">
          <div class="field">
            <label>Nombre del Proyecto</label>
            <input type="text" class="ui" placeholder="Nombre del Proyecto" aria-label="Search" name='q'>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui form">
          <div class="field">
            <label>Categoría</label>
            <select class="ui dropdown selection" id="id_pro_category" name="id_pro_category" class="opt">
              <option value="" selected disabled>Categoría</option>
              {% for cat in category %}
              <option value="{{cat.category}}">{{cat.category}}</option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="ui form">
          <div class="field">
            <label>Subcategoría</label>
            <select class="ui dropdown selection" id="id_pro_subcategory" name="id_pro_subcategory" >
              <option value="" selected disabled>Subcategoría</option>
              {% for subcat in subcategory %}
              <option value="{{subcat.subcategory}}">{{subcat.subcategory}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui form">
          <div class="field">
          <label>Estado</label>
            <select class="ui dropdown selection" id="id_pro_state" name="id_pro_state">
              <option value="" selected disabled>Estado</option>
              {% for st in state %}
              <option value="{{st.state}}">{{st.state}}</option>
              {% endfor %}
            </select>
          </div>
        </div>

        <div class="ui form">
          <div class="field">
          <label>Municipio</label>
            <select class="ui dropdown selection" id="id_pro_city" name="id_pro_city">
              <option value="" selected disabled>Municipio</option>
              {% for cit in city %}
              <option value="{{cit.city}}">{{cit.city}}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui form">
          <div class="field">
            <label>Tipo</label>
            <input type="radio" name="id_pro_group" value="proyectos"> Proyectos<br>
            <input type="radio" name="id_pro_group" value="grupos"> Grupos<br>
          </div>
        </div>
      </div>
      <div class="column">
        <div class="ui form">
          <div class="field">
            <button class="ui big teal button" id="go" type="submit">Buscar</button>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

<br />
<div class="ui four column doubling stackable grid container">
    {% for project in projects|dictsort:"id" reversed %}
        <div class="column">
          <div class="ui link cards">
            <div class="ui card">
            <a class="image"href="{% url 'project_app:project' project.id project.pro_name|slugify %}">
                {% if project.pro_img %}
                  <img src="{{project.pro_img.url}}">
                {% else %}
                  <img src="https://semantic-ui.com/images/wireframe/image.png">
                {% endif %}
              </a>
            <div class="content">
              <a class="header" href="{% url 'project_app:project' project.id project.pro_name|slugify %}">{{project.pro_name}} </a>
              <div class="meta">
                <i class="tags icon"></i>
                      {{project.pro_category}}, {{project.pro_subcategory}}.
              </div>
              <div class="meta">
                <i class="map marker alternate icon"></i>
                      {{project.pro_city}}, {{project.pro_state}}.
              </div>
              <div class="description">
                   <p>{{project.pro_description | truncatewords:50 |safe}} </p>
                 </div>
            </div>
            <div class="extra content">
              <span class="right floated">
                {{project.pro_creation_date}}
              </span>
              <span>

                <a class="ui image label" href="{% url 'profiles_app:detail' project.pro_user.profile.user.username %}">
                {%if project.pro_user.profile.avatar%}
                <img class="ui avatar image" src="{{project.pro_user.profile.avatar.url}}">
                {{project.pro_user}}
                {%else%}
                <img class="ui avatar image" src="https://semantic-ui.com/images/avatar2/small/lena.png">
                {{request.user.profile.user}}
                {%endif%}
                </a>

                   <div class="row mt-3">
                     <div class="col-md-9 mx-auto">
                       <div class="description">

                         {% if request.user == project.pro_user %}
                               <a href="{% url 'project_app:applications' project.id %}">Ver solicitudes</a>
                             | <a href="{% url 'project_app:update' project.id %}">Editar</a>
                             | <a href="{% url 'project_app:delete' project.id %}">Borrar</a>
                           {% endif %}

                           <script type="text/javascript">
                           console.log("{% url 'project_app:project' project.id project.pro_name|slugify %}");

                           </script>

                       </div>
                     </div>
                   </div>
                 </span>
            </div>
            <div class="ui attached bottom buttons">
                <a class="ui teal button" href="{% url 'project_app:project' project.id project.pro_name|slugify %}"><i class="pencil alternate icon"></i>Leer más</a>
              </div>
          </div>
          </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

{% block js_block %}
<script src="{% static "css/semantic/out/semantic.min.js" %}"></script>
<script type="text/javascript">
  $("#id_pro_state").change(function () {
    var url = $("#projectForm").attr("data-cities-url");
    console.log(url);
    var countryId = $(this).val();
    //console.log(countryId);
    $.ajax({
      url: url,
      data: {
        'country': countryId
      },
      success: function (data) {
            //console.log("ENTRA DOS")
            //console.log(data);
        $("#id_pro_city").html(data);
      }
    });
  });

  $("#id_pro_category").change(function () {
      //console.log("ENTRA");
    var url = $("#projectForm").attr("data-subcategories-url");
    //console.log(url);
    var countryId = $(this).val();
    //console.log(countryId);
    $.ajax({
      url: url,
      data: {
        'category': countryId
      },
      success: function (data) {
        $("#id_pro_subcategory").html(data);
      }
    });
  });
</script>


{% endblock %}