nss/account_app/urls.py
###Last modified by Martín Helmut on Oct 20,2018
from django.urls import path, include
from account_app import views
from project_app.urls import projects_patterns
from .views import ProfileAccountUpdate

app_name = 'account_app'
urlpatterns=[

    #path('', views.see_project, name = 'see_project'),
    path('registrar/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('profile/', ProfileAccountUpdate.as_view(), name="profile"),

    #path('create_profile/',views.form_profile, name='form_profile'),

    # path('my_projects/', MyProjectsView.as_view(), name='my_projects'),
    # path('projects/',include(projects_patterns)),
]

nss/nss/urls.py
#Last modified by César Buenfil on Oct 19,2018

"""nss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an imlport:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from account_app import views
from django.conf import settings
from django.conf.urls.static import static
from project_app.urls import projects_patterns
from profiles_app.urls import profiles_patterns
from messages_app.urls import  messages_app_patterns
#SOCIAL AUTH
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
    path('',views.IndexView.as_view(),name='index'), #Despliega lo de la funcion index en appOne/views.py/def index
    path('user/', include('account_app.urls')),
    path('search/', include('search_app.urls')),

    #path('crearProyecto/',include('appOne.urls')),
    #path('createProyect/',views.form_name_view,name='form_name'),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    #path('create_profile/',views.form_profile, name='form_profile'),
    path('project_app/',include(projects_patterns)),
    path('', include('django.contrib.auth.urls')), # EMAIL RESET
    path('oauth/', include('social_django.urls', namespace="social")),
    path('profiles_app/', include(profiles_patterns)),
    path('messages_app/', include(messages_app_patterns)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#models
#Help us incorporate a database into a django project

nss/project_app/urls.py
from django.urls import path
from .views import ProjectsListView,GroupCreate,DataRepGoogle,ApplicationsDetailView,delete,accept,button_text, change_user_project_status ,ProjectDetailView, ProjectCreate, ProjectUpdate, ProjectDelete, DataRep, ProjectRolCreate
from project_app import views
app_name="project_app"
projects_patterns = ([
    path('p/', ProjectsListView.as_view(), name='projects'),
    path('<int:pk>/a/', ApplicationsDetailView.as_view(), name='applications'),
    path('<int:pk>/<slug:slug>/', ProjectDetailView.as_view(), name='project'),
    path('ajax/change_user_project_status/', views.change_user_project_status, name='change_user_project_status'),
    path('ajax/button_text/', views.button_text, name='button_text'),
    path('ajax/accept/', views.accept, name='accept'),
    path('ajax/delete/', views.delete, name='delete'),
    path('create/', ProjectCreate.as_view(), name='create'),
    path('createGroup/', GroupCreate.as_view(), name='create_group'),
    path('DataRep/', views.DataRep, name='DataRep'),
    path('DataRepGoogle/', views.DataRepGoogle, name='DataRepGoogle'),
    path('update/<int:pk>/', ProjectUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDelete.as_view(), name='delete'),
    path('createRolProyecto/<int:pk>/<slug:slug>/', ProjectRolCreate.as_view(), name = 'form_rol_project'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
    path('like/',views.like_post, name ="like_post"),

], 'project_app')

nss/projects/urls.py
from django.urls import path
from .views import ProjectsListView, ProjectDetailView, ProjectCreate, ProjectUpdate, ProjectDelete


projects_patterns = ([
    path('', ProjectsListView.as_view(), name='projects'),
    path('<int:pk>/<slug:slug>/', ProjectDetailView.as_view(), name='project'),
    path('create/', ProjectCreate.as_view(), name='create'),
    path('update/<int:pk>/', ProjectUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDelete.as_view(), name='delete'),
], 'projects')

nss/project/models.py
from django.db import models
from ckeditor.fields import RichTextField

#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title

class Project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')
    pro_description = models.TextField(max_length=800,default='')
    pro_video = EmbedVideoField() # models.URLField()
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_location = models.ForeignKey('location', on_delete=models.PROTECT,default='')
    pro_roles = models.ManyToManyField('rolInfo') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields
    
    def __str__(self):
        return self.pro_name

nss/project_app/models.py
"""
Last modified: ANgélica Güemes
date: November 8
Time: 8:40
"""
from django.db import models
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title

class category(models.Model):
     category = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.category

class subcategory(models.Model):
     subcategory = models.CharField(primary_key=True,max_length = 50, unique = True, default='')
     category = models.ForeignKey('category', on_delete=models.PROTECT,default='')

     def __str__(self):
        return self.subcategory

class state(models.Model): #estado
     state = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.state

class city(models.Model): #ciudad
     city = models.CharField(primary_key=True,max_length = 50, unique = True, default='')
     state = models.ForeignKey('state', on_delete=models.PROTECT,default='')
     def __str__(self):
        return self.city

class rolInfo(models.Model):#info del rol
    rol_name =  models.CharField(max_length = 150,  default='')
    rol_name_other=models.CharField(max_length = 150,  default='', blank=True)
    rol_due_date = models.DateField()
    rol_amount = models.PositiveIntegerField(default=1)
    rol_description = models.TextField(max_length=800, default='')
    rol_city = models.ForeignKey('city', on_delete=models.PROTECT,default='')
    rol_state = models.ForeignKey('state', on_delete=models.PROTECT,default='')


    def __str__(self):
        return self.rol_name

class project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')
    #Import RichTextField
    pro_description = RichTextField(verbose_name="Descripción", max_length=5000)
    pro_video = EmbedVideoField() # models.URLField()
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_img = models.ImageField(default='', upload_to='pro_img', blank=True)# null=true se pone null en la base de datos como entrada
    pro_group = models.BooleanField()
    likes = models.ManyToManyField(User,related_name="likes",blank=True)
    pro_save_times = models.PositiveIntegerField(default=0)

    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_subcategory = models.ForeignKey('subcategory', on_delete=models.PROTECT,default='')

    pro_city = models.ForeignKey('city', on_delete=models.PROTECT,default='')
    pro_state = models.ForeignKey('state', on_delete=models.PROTECT,default='')

    pro_roles = models.ManyToManyField('rolInfo', through='project_rol') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields

    pro_user = models.ForeignKey(User, on_delete=models.CASCADE, default="", blank=True, null=True)

    class Meta:
            verbose_name = "project_app"
            verbose_name_plural = "project_app"
            ordering = ['order','pro_name']

    def __str__(self):
        return self.pro_name

    def total_likes(self):
        return self.likes.count()



class projectImg(models.Model):#Ya no se usa
    pro_img = models.ImageField(default='', upload_to='pro_img', blank=True)
    pro = models.ForeignKey('project', on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.pro_img)

class project_rol(models.Model):#Tabla NN
    id= models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    pro = models.ForeignKey('project', related_name='project', on_delete=models.CASCADE,default='')
    rol= models.ForeignKey('rolInfo', related_name='rolInfo', on_delete=models.CASCADE,default='')
    def __str__(self):
        return str(self.rol)

class user_project(models.Model):
    up_project = models.ForeignKey('project', related_name='up_project', on_delete=models.CASCADE,default='')
    up_user = models.ForeignKey(User, on_delete=models.CASCADE, default="", blank=True, null=True)
    up_rolInfo =  models.ForeignKey('rolInfo', related_name='up_rolInfo', on_delete=models.CASCADE,default='')
    up_status = models.ForeignKey('status', related_name='upstatus', on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.up_project)

class status(models.Model):
    status= models.CharField(primary_key=True,max_length = 50, unique = True, default='')
    status_text= models.CharField(max_length=40,default='')
    def __str__(self):
        return str(self.status)

nss/projects/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField

#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title
class category(models.Model):
     category = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.category

class location(models.Model):
     location = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.location

class rol(models.Model):
    rol = models.CharField(primary_key=True, max_length = 15, unique = True, default='')

    def __str__(self):
        return self.rol

class rolInfo(models.Model):
    rol_name =  models.ForeignKey(rol, on_delete=models.CASCADE)
    rol_due_date = models.DateField()
    rol_amount = models.PositiveIntegerField(default=1)
    rol_description = models.TextField(max_length=800, default='')
    rol_location = models.ForeignKey('location', on_delete=models.PROTECT,default='')

    def __str__(self):
        return self.rol_description


class Project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')

    #Import RichTextField
    pro_description = RichTextField(verbose_name="Descripción")
    pro_video = EmbedVideoField() # models.URLField()
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_location = models.ForeignKey('location', on_delete=models.PROTECT,default='')
    pro_roles = models.ManyToManyField('rolInfo') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields

    class Meta:
            verbose_name = "projects"
            verbose_name_plural = "projects"
            ordering = ['order','pro_name']

    def __str__(self):
        return self.pro_name

nss/projects/views.py
from .models import Project
from .forms import CreateProjectForm
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.template.defaultfilters import slugify

# Create your views here.

#Returns a complete list of projects
class ProjectsListView(ListView):
    model = Project

##Return a pack of projects
class ProjectDetailView(DetailView):
    model = Project

##Creates a project with the given arguments
class ProjectCreate(CreateView):
    model = Project
    form_class = CreateProjectForm
    # success_url=reverse_lazy('projects:projects')
    def get_success_url(self):
        return reverse_lazy('projects:project', args=[self.object.id, slugify(self.object.pro_name)])

class ProjectUpdate(UpdateView):
    model = Project
    fields = ['pro_name','pro_description','pro_video', 'pro_about_us', 'pro_phrase', 'pro_creation_date', 'pro_category', 'pro_location', 'pro_roles']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('projects:update', args=[self.object.id]) + '?ok'

class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('projects:projects')

nss/project_app/templates/project_app/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.city }}</option>
{% endfor %}

nss/project_app/templates/project_app/group_form.html
<!--
"""
Last modified: ANgélica Güemes
date: November 7
Time: 8:15
"""
-->
{% extends "base.html" %}
{% load staticfiles %}
{% block processes_block %}
<script type ="text/javascript" src="{% static "js/extras/processes.js" %}"></script>  <!--Este link hace que no jale el datepicker de create_project.html-->
{% endblock %}
{% block title %}Teem: Crear Grupo{% endblock %}
{% block body_block %}
    <div class="container">

      <div class="ui grid container">
        <div class="ui vertical segment">
          <div class="ui header">
            <!--Crear Proyecto-->
          </div>
          <form method="POST" id="projectForm" enctype="multipart/form-data" class="ui form segment" data-cities-url="{% url 'project_app:ajax_load_cities' %}" data-subcategories-url="{% url 'project_app:ajax_load_subcategories' %}" >
          {% csrf_token %}

          <h2 class="ui dividing header">Crea tu grupo</h2>

                    <div class="field">
                      <div class="two fields">
                        <div class="field">
                          {{form.pro_group}}

                          <label>{{form.pro_name.label}}</label>
                          {{form.pro_name}}
                          {{form.pro_name.errors}}
                        </div>
                        <div class="field">
                          <label>{{form.pro_creation_date.label}}</label>
                          {{form.pro_creation_date}}
                          {{form.pro_creation_date.errors}}
                        </div>
                      </div>
                    </div>

                    <div class="field">
                      <div class="two fields">
                        <div class="field">
                          <label>{{form.pro_category.label}} </label>
                          {{form.pro_category}}
                          {{form.pro_category.errors}}
                        </div>
                        <div class="field">
                          <label>{{form.pro_category.label}}</label>
                          {{form.pro_subcategory}}
                          {{form.pro_subcategory.errors}}
                        </div>
                      </div>
                    </div>

                    <div class="field">
                      <label>{{form.pro_description.label}}</label>
                      <div class="fields">
                        <div class="sixteen wide field">
                          <div class="ui fluid">
                            {{form.pro_description}}
                            {{form.pro_description.errors}}
                          </div>
                        </div>
                      </div>
                    </div>

                    <div class="field">
                      <div class="two fields">
                        <div class="field">
                          <label>{{form.pro_video.label}}</label>
                          {{form.pro_video}}
                          {{form.pro_video.errors}}
                        </div>
                        <div class="field">
                          <label>{{form.pro_img.label}}</label>
                          {{form.pro_img}}
                          {{form.pro_img.errors}}
                        </div>
                      </div>
                    </div>

                    <div class="field">
                        <h4><label>Ubicación del proyecto</label>  </h4>
                      <div class="two fields">
                        <div class="field">
                          <label>{{form.pro_state.label}}</label>
                          {{form.pro_state}}
                          {{form.pro_state.errors}}
                        </div>
                        <div class="field">
                          <label> {{form.pro_city.label}}</label>
                          	{{form.pro_city}}
                            {{form.pro_city.errors}}
                        </div>
                      </div>
                    </div>

                    <div class="field">
                      <div class="two fields">
                        <div class="field">
                          <label>{{form.pro_about_us.label}}</label>
                          {{form.pro_about_us}}
                          {{form.pro_about_us.errors}}
                        </div>
                        <div class="field">
                          <label>{{form.pro_phrase.label}}</label>
                            {{form.pro_phrase}}
                            {{form.pro_phrase.errors}}
                        </div>
                      </div>
                    </div>

<!--
                     <div class="ui segment">
                      <div class="field">
                        <div class="ui toggle checkbox">
                          <input type="checkbox" name="gift" tabindex="0" class="hidden">
                          <label>Recibir correo de confirmación</label>
                        </div>
                      </div>
                    </div>

-->



            <input type="submit" class=" ui green inverted button" value="Crear grupo">

          <!--  <input type="submit" class="ui green inverted button value="Crear grupo">-->

          </form>
        </div>
      </div>

    </div>
{% endblock %}

{% block js_block %}
<script src="{% static "css/semantic/out/semantic.min.js" %}"></script>
<script type="text/javascript">

  $(function() {
  document.getElementById("id_pro_group").value = True;
  $("#id_pro_group").val("True");
    var dateToday = new Date();
    $('input[class="datepicker"]').daterangepicker({
      singleDatePicker: true,
      showDropdowns: true,
      maxDate: dateToday,
      locale: {
         format: 'YYYY-MM-DD'
        }
    });
  });
</script>
<script type='text/javascript'>
  $("#id_pro_state").change(function () {
    console.log("ENTRA");
  var url = $("#projectForm").attr("data-cities-url");
  console.log(url);
  var countryId = $(this).val();
  console.log(countryId);
  $.ajax({
    url: url,
    data: {
      'country': countryId
    },
    success: function (data) {
          console.log("ENTRA DOS")
          console.log(data);
      $("#id_pro_city").html(data);
    }
  });
  });
    </script>
    <script type='text/javascript'>
      $("#id_pro_category").change(function () {
        console.log("ENTRA");
      var url = $("#projectForm").attr("data-subcategories-url");
      console.log(url);
      var countryId = $(this).val();
      console.log(countryId);
      $.ajax({
        url: url,
        data: {
          'category': countryId
        },
        success: function (data) {
              console.log("ENTRA DOS")
              console.log(data);
          $("#id_pro_subcategory").html(data);
        }
      });
      });
        </script>
{% endblock %}

nss/project_app/templates/project_app/like_section.html
{{ total_likes }} Like{{ total_likes|pluralize }}
{% if request.user.is_authenticated %}
<form action="" method="post">
  {% csrf_token %}
  {% if is_liked %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="ui fluid red small button cnt">Dislike</button>
  {% else %}
    <button type="submit" id="like" name="post_id" value="{{ post.id }}" class="ui fluid primary small button cnt">Like</button>
  {% endif %}
</form>
{% endif %}

nss/project_app/templates/project_app/project_confirm_delete.html
{% extends "base.html" %}
{% load staticfiles %}
{% block processes_block %}
<script type ="text/javascript" src="{% static "js/extras/processes.js" %}"></script>  <!--Este link hace que no jale el datepicker de create_project.html-->
{% endblock %}
{% block body_block %}
  <form class="ui form"  method="post">
    {% csrf_token %}
    <br>
    <h1 class="ui centered grid container">¿Seguro que deseas borrar "{{object}}" ?</h1>

    <div class="ui centered grid container">

    <input   class="ui grey basic button"type="submit" name=""  value="Sí, borrar">
    </div>

  </form>
{% endblock %}

nss/project_app/templates/project_app/project_update_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block processes_block %}
<script type ="text/javascript" src="{% static "js/extras/processes.js" %}"></script>  <!--Este link hace que no jale el datepicker de create_project.html-->
{% endblock %}
{% block body_block %}
    <div class="container">
      <!--<h1 class="content">Actualiza tu proyecto</h1>--><br><br>

      {% if 'ok' in request.GET %}
      <div class="ui mini modal">
        <div class="ui icon header">
          <i class="archive icon"></i>
          El proyecto se actualizó con éxito.
        </div>
        <div class="content">
          <p class="ui centered grid container">Los cambios se han guardado ¿Desea seguir editando?</p>
        </div>
        <div class="actions">
          <a class="ui red inverted cancel inverted button" href="{% url 'project_app:project' project.id project.pro_name|slugify %}">
            <i class="remove icon"></i>
            No
          </a>
          <div class="ui green ok inverted button">
            <i class="checkmark icon"></i>
            Sí
          </div>
        </div>
      </div>
      {% endif %}

      <form method="POST" id="projectForm"  class="ui form container segment" enctype="multipart/form-data"class="ui form" data-cities-url="{% url 'project_app:ajax_load_cities' %}" data-subcategories-url="{% url 'project_app:ajax_load_subcategories' %}" >
      {% csrf_token %}


      <h3>Actualizar información del proyecto</h3>

                          <div class="field">
                            <div class="two fields">
                              <div class="field">
                                <label>{{form.pro_name.label}}</label>
                                {{form.pro_name}}
                              </div>
                              <div class="field">
                                <label>{{form.pro_creation_date.label}}</label>
                                {{form.pro_creation_date}}
                              </div>
                            </div>
                          </div>

                          <div class="field">
                            <div class="two fields">
                              <div class="field">
                                <label>{{form.pro_category.label}} </label>
                                {{form.pro_category}}
                              </div>
                              <div class="field">
                                <label>{{form.pro_category.label}}</label>
                                {{form.pro_subcategory}}
                              </div>
                            </div>
                          </div>

                          <div class="field">
                            <label>{{form.pro_description.label}}</label>
                            <div class="fields">
                              <div class="sixteen wide field">
                                <div class="ui fluid">
                                  {{form.pro_description}}
                                </div>
                              </div>
                            </div>
                          </div>

                          <div class="field">
                            <label>{{form.pro_video.label}}</label>
                            <div class="one field">
                              <div class="field">
                                {{form.pro_video}}
                              </div>
                            </div>
                          </div>

                          <div class="field">
                              <h4><label>Ubicación del proyecto</label>  </h4>
                            <div class="two fields">
                              <div class="field">
                                <label>{{form.pro_state.label}}</label>
                                {{form.pro_state}}
                              </div>
                              <div class="field">
                                <label> {{form.pro_city.label}}</label>
                                	{{form.pro_city}}
                              </div>
                            </div>
                          </div>

                          <div class="field">
                            <div class="two fields">
                              <div class="field">
                                <label>{{form.pro_about_us.label}}</label>
                                {{form.pro_about_us}}
                              </div>
                              <div class="field">
                                <label>{{form.pro_phrase.label}}</label>
                                  {{form.pro_phrase}}
                              </div>
                            </div>
                          </div>

        <input type="submit" class="positive ui button" value="Actualiza">


      </form>
    </div>
{% endblock %}

{% block js_block %}
<script src="{% static "css/semantic/out/semantic.min.js" %}"></script>
<script type="text/javascript">
  $(function() {
    $('input[id="id_pro_creation_date"]').daterangepicker({
      singleDatePicker: true,
      showDropdowns: true,
      locale: {
         format: 'YYYY-MM-DD'
        }
    });
  });
  $('.mini.modal')
  .modal('show')
;
  //document.getElementById('fieldWrapper').innerHTML.setAttribute("multiple", "multiple");
</script>
<script type='text/javascript'>
  $("#id_pro_state").change(function () {
    console.log("ENTRA");
  var url = $("#projectForm").attr("data-cities-url");
  console.log(url);
  var countryId = $(this).val();
  console.log(countryId);
  $.ajax({
    url: url,
    data: {
      'country': countryId
    },
    success: function (data) {
          console.log("ENTRA DOS")
          console.log(data);
      $("#id_pro_city").html(data);
    }
  });
  });
    </script>
  </script>
  <script type='text/javascript'>
    $("#id_pro_category").change(function () {
      console.log("ENTRA");
    var url = $("#projectForm").attr("data-subcategories-url");
    console.log(url);
    var countryId = $(this).val();
    console.log(countryId);
    $.ajax({
      url: url,
      data: {
        'category': countryId
      },
      success: function (data) {
            console.log("ENTRA DOS")
            console.log(data);
        $("#id_pro_subcategory").html(data);
      }
    });
    });
      </script>
{% endblock %}

nss/project_app/templates/project_app/subcategory_dropdown_list_options.html
<option value="">---------</option>
{% for subcategory in subcategories %}
<option value="{{ subcategory.pk }}">{{ subcategory.subcategory }}</option>
{% endfor %}