nss/account_app/urls.py
###Last modified by Martín Helmut on Oct 20,2018
from django.urls import path, include
from account_app import views
from project_app.urls import projects_patterns
from .views import ProfileAccountUpdate

app_name = 'account_app'
urlpatterns=[

    #path('', views.see_project, name = 'see_project'),
    path('registrar/',views.register,name='register'),
    path('login/',views.user_login,name='user_login'),
    path('profile/', ProfileAccountUpdate.as_view(), name="profile"),

    #path('create_profile/',views.form_profile, name='form_profile'),

    # path('my_projects/', MyProjectsView.as_view(), name='my_projects'),
    # path('projects/',include(projects_patterns)),
]

nss/nss/urls.py
#Last modified by César Buenfil on Oct 19,2018

"""nss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an imlport:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from account_app import views
from django.conf import settings
from django.conf.urls.static import static
from project_app.urls import projects_patterns
from profiles_app.urls import profiles_patterns
from messages_app.urls import  messages_app_patterns
#SOCIAL AUTH
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('i18n/',include('django.conf.urls.i18n')),
    path('',views.IndexView.as_view(),name='index'), #Despliega lo de la funcion index en appOne/views.py/def index
    path('user/', include('account_app.urls')),
    path('search/', include('search_app.urls')),

    #path('crearProyecto/',include('appOne.urls')),
    #path('createProyect/',views.form_name_view,name='form_name'),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    #path('create_profile/',views.form_profile, name='form_profile'),
    path('project_app/',include(projects_patterns)),
    path('', include('django.contrib.auth.urls')), # EMAIL RESET
    path('oauth/', include('social_django.urls', namespace="social")),
    path('profiles_app/', include(profiles_patterns)),
    path('messages_app/', include(messages_app_patterns)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#models
#Help us incorporate a database into a django project

nss/project_app/urls.py
from django.urls import path
from .views import ProjectsListView,GroupCreate,DataRepGoogle,ApplicationsDetailView,delete,accept,button_text, change_user_project_status ,ProjectDetailView, ProjectCreate, ProjectUpdate, ProjectDelete, DataRep, ProjectRolCreate
from project_app import views
app_name="project_app"
projects_patterns = ([
    path('p/', ProjectsListView.as_view(), name='projects'),
    path('<int:pk>/a/', ApplicationsDetailView.as_view(), name='applications'),
    path('<int:pk>/<slug:slug>/', ProjectDetailView.as_view(), name='project'),
    path('ajax/change_user_project_status/', views.change_user_project_status, name='change_user_project_status'),
    path('ajax/button_text/', views.button_text, name='button_text'),
    path('ajax/accept/', views.accept, name='accept'),
    path('ajax/delete/', views.delete, name='delete'),
    path('create/', ProjectCreate.as_view(), name='create'),
    path('createGroup/', GroupCreate.as_view(), name='create_group'),
    path('DataRep/', views.DataRep, name='DataRep'),
    path('DataRepGoogle/', views.DataRepGoogle, name='DataRepGoogle'),
    path('update/<int:pk>/', ProjectUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDelete.as_view(), name='delete'),
    path('createRolProyecto/<int:pk>/<slug:slug>/', ProjectRolCreate.as_view(), name = 'form_rol_project'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
    path('like/',views.like_post, name ="like_post"),

], 'project_app')

nss/projects/urls.py
from django.urls import path
from .views import ProjectsListView, ProjectDetailView, ProjectCreate, ProjectUpdate, ProjectDelete


projects_patterns = ([
    path('', ProjectsListView.as_view(), name='projects'),
    path('<int:pk>/<slug:slug>/', ProjectDetailView.as_view(), name='project'),
    path('create/', ProjectCreate.as_view(), name='create'),
    path('update/<int:pk>/', ProjectUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', ProjectDelete.as_view(), name='delete'),
], 'projects')

nss/project/models.py
from django.db import models
from ckeditor.fields import RichTextField

#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title

class Project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')
    pro_description = models.TextField(max_length=800,default='')
    pro_video = EmbedVideoField() # models.URLField()
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_location = models.ForeignKey('location', on_delete=models.PROTECT,default='')
    pro_roles = models.ManyToManyField('rolInfo') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields
    
    def __str__(self):
        return self.pro_name

nss/project_app/models.py
"""
Last modified: ANgélica Güemes
date: November 8
Time: 8:40
"""
from django.db import models
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


#class Page(models.Model):
#    title = models.CharField(verbose_name="Título", max_length=200)
#    content = RichTextField(verbose_name="Contenido")
#    order = models.SmallIntegerField(verbose_name="Orden", default=0)
#    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
#    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")
#
#    class Meta:
#        verbose_name = "página"
#        verbose_name_plural = "páginas"
#        ordering = ['order', 'title']
#
#    def __str__(self):
#        return self.title

class category(models.Model):
     category = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.category

class subcategory(models.Model):
     subcategory = models.CharField(primary_key=True,max_length = 50, unique = True, default='')
     category = models.ForeignKey('category', on_delete=models.PROTECT,default='')

     def __str__(self):
        return self.subcategory

class state(models.Model): #estado
     state = models.CharField(primary_key=True,max_length = 50, unique = True, default='')

     def __str__(self):
        return self.state

class city(models.Model): #ciudad
     city = models.CharField(primary_key=True,max_length = 50, unique = True, default='')
     state = models.ForeignKey('state', on_delete=models.PROTECT,default='')
     def __str__(self):
        return self.city

class rolInfo(models.Model):#info del rol
    rol_name =  models.CharField(max_length = 150,  default='')
    rol_name_other=models.CharField(max_length = 150,  default='', blank=True)
    rol_due_date = models.DateField()
    rol_amount = models.PositiveIntegerField(default=1)
    rol_description = models.TextField(max_length=800, default='')
    rol_city = models.ForeignKey('city', on_delete=models.PROTECT,default='')
    rol_state = models.ForeignKey('state', on_delete=models.PROTECT,default='')


    def __str__(self):
        return self.rol_name

class project(models.Model):
    #Info del proyecto
    pro_name = models.CharField(max_length=40,default='')
    #Import RichTextField
    pro_description = RichTextField(verbose_name="Descripción", max_length=5000)
    pro_video = EmbedVideoField() # models.URLField()
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    pro_about_us = models.TextField(max_length=800, default='')
    pro_phrase = models.CharField(max_length=200, default='')
    pro_creation_date = models.DateField()
    pro_img = models.ImageField(default='', upload_to='pro_img', blank=True)# null=true se pone null en la base de datos como entrada
    pro_group = models.BooleanField()
    likes = models.ManyToManyField(User,related_name="likes",blank=True)
    pro_save_times = models.PositiveIntegerField(default=0)

    pro_category = models.ForeignKey('category', on_delete=models.PROTECT,default='')
    pro_subcategory = models.ForeignKey('subcategory', on_delete=models.PROTECT,default='')

    pro_city = models.ForeignKey('city', on_delete=models.PROTECT,default='')
    pro_state = models.ForeignKey('state', on_delete=models.PROTECT,default='')

    pro_roles = models.ManyToManyField('rolInfo', through='project_rol') # https://stackoverflow.com/questions/2216974/django-modelform-for-many-to-many-fields

    pro_user = models.ForeignKey(User, on_delete=models.CASCADE, default="", blank=True, null=True)

    class Meta:
            verbose_name = "project_app"
            verbose_name_plural = "project_app"
            ordering = ['order','pro_name']

    def __str__(self):
        return self.pro_name

    def total_likes(self):
        return self.likes.count()



class projectImg(models.Model):#Ya no se usa
    pro_img = models.ImageField(default='', upload_to='pro_img', blank=True)
    pro = models.ForeignKey('project', on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.pro_img)

class project_rol(models.Model):#Tabla NN
    id= models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    pro = models.ForeignKey('project', related_name='project', on_delete=models.CASCADE,default='')
    rol= models.ForeignKey('rolInfo', related_name='rolInfo', on_delete=models.CASCADE,default='')
    def __str__(self):
        return str(self.rol)

class user_project(models.Model):
    up_project = models.ForeignKey('project', related_name='up_project', on_delete=models.CASCADE,default='')
    up_user = models.ForeignKey(User, on_delete=models.CASCADE, default="", blank=True, null=True)
    up_rolInfo =  models.ForeignKey('rolInfo', related_name='up_rolInfo', on_delete=models.CASCADE,default='')
    up_status = models.ForeignKey('status', related_name='upstatus', on_delete=models.CASCADE,default='')

    def __str__(self):
        return str(self.up_project)

class status(models.Model):
    status= models.CharField(primary_key=True,max_length = 50, unique = True, default='')
    status_text= models.CharField(max_length=40,default='')
    def __str__(self):
        return str(self.status)

nss/account_app/views.py
### Last modified by César Buenfil on Oct 14,2018

from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.mail import send_mail
from . import forms
from account_app.forms import  UserForm, createProfileForm, ProfileForm
from django.urls import reverse, reverse_lazy
from urllib.parse import urlencode
from project_app.models import project, projectImg, project, rolInfo, city,state, category, subcategory
from project_app import models
from django.db.models import Q
from functools import reduce
from django.views import generic
from braces.views import SelectRelatedMixin
import operator

from django.utils.decorators import method_decorator
#login
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

#Class Based views
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView, UpdateView,
                                DeleteView)
from .models import Profile

# Create your views here.
class IndexView(SelectRelatedMixin, generic.ListView):
    template_name = 'account_app/index.html'
    context_object_name = 'projects'
    model = models.project
    select_related = ("pro_category", "pro_subcategory", "pro_city", "pro_state")

def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)

@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True

        else:
            print(user_form.errors)

    else:
        user_form = UserForm()

    return render(request,'account_app/registration.html',{'user_form':user_form,
                                                       'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not Active")

        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request,'account_app/login.html',{})

###Class Based Views

@method_decorator(login_required, name='dispatch')
class ProfileAccountUpdate(UpdateView):
    form_class=ProfileForm
    success_url = reverse_lazy('account_app:profile')
    template_name='account_app/profile_form.html'
    def get_object(self):
        profile_obj, create = Profile.objects.get_or_create(user=self.request.user)
        return profile_obj



"""
    def form_project(request):
        form = forms.formProject()
        if request.method == 'POST':
            form = forms.formProject(request.POST)
            if form.is_valid():
                # DO SOMETHING CODE
                print("VALIDATION SUCCESS!")
                #print("NAME: "+form.cleaned_data['name'])
                #recipients=[]
                #if ProConfirmation:
                    #print("Enviar email!")
                #    send_mail('subject', 'message', 'A01421467@itesm.mx', 'angieguemes@gmail.com')
                #    return HttpResponseRedirect('/thanks/')
        return render(request,'app_one/createPro.html',{'form':form})
"""

nss/projects/views.py
from .models import Project
from .forms import CreateProjectForm
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.template.defaultfilters import slugify

# Create your views here.

#Returns a complete list of projects
class ProjectsListView(ListView):
    model = Project

##Return a pack of projects
class ProjectDetailView(DetailView):
    model = Project

##Creates a project with the given arguments
class ProjectCreate(CreateView):
    model = Project
    form_class = CreateProjectForm
    # success_url=reverse_lazy('projects:projects')
    def get_success_url(self):
        return reverse_lazy('projects:project', args=[self.object.id, slugify(self.object.pro_name)])

class ProjectUpdate(UpdateView):
    model = Project
    fields = ['pro_name','pro_description','pro_video', 'pro_about_us', 'pro_phrase', 'pro_creation_date', 'pro_category', 'pro_location', 'pro_roles']
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('projects:update', args=[self.object.id]) + '?ok'

class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('projects:projects')

nss/account_app/templates/account_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">

             <title>{% block title %}{% endblock %}</title>

            <link href="https://fonts.googleapis.com/css?family=Fira+Sans" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
            <link rel="stylesheet" href="{% static "css/styles.css" %}">
            <link rel="stylesheet" href="{% static "css/semantic/out/semantic.css" %}">
            <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
            <link rel="stylesheet" href="{% static "css/extras/processes.css" %}">
            <link rel="stylesheet" href="{% static "css/styles.css" %}">
            <script type="text/javascript" src="{% static "js/extras/processes.js" %}"></script>
              <script src="{% static "css/semantic/out/semantic.min.js" %}"></script>
            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
            <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
            <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
            <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
        </head>
    <body class="bg-gray">
        <!-- Static navbar -->
        <div class="ui borderless menu stackable shadow number1">
            <div class="ui container">
                <div class="header item">
                    <a href="{% url 'index' %}" class="item"><img class="logo" src="{% static "img/logo.png" %}"><i class="users icon"></i></a>
                </div>

                {% if user.is_authenticated %}
                <div class="ui right simple dropdown item">
                  <i class="edit icon"></i>Projects
                  <i class="dropdown icon"></i>
                  <div class="menu">
                    <a class="item" href="{% url 'account_app:form_project' %}">Crear Proyecto</a>
                    <a class="item" href="{% url 'account_app:form_project2' %}">Alt Crear Proyecto</a>
                  </div>
                </div>

    			      <a class="item" href="{% url 'project_app:projects' %}"><i class="folder icon"></i>MisProyectos</a>
    			      <a class="item" href="{% url 'project_app:create' %}"><i class="pencil alternate icon"></i>Crear</a>
                <a class="item"><i class="bell icon"></i></a>
                <div class="ui simple dropdown item">
                  <i class="user icon"></i>User
                  <i class="dropdown icon"></i>
                  <div class="menu">
                    <a class="item"><i class="address card outline icon"></i> View Profile</a>
                    <a class="item"><i class="edit icon"></i> Edit Profile</a>
                    <a class="item"><i class="globe icon"></i> Choose Language</a>
                    <a class="item"><i class="settings icon"></i> Account Settings</a>
                    <a class="item" href="{% url 'logout' %}"><i class="power off icon"></i>Logout</a>
                  </div>
                </div>
              </div>
                {% else %}
                <a class="item ui right floated" href="{% url 'account_app:user_login' %}">Log in</a>
                <div class="item">
                  <a class="ui primary button" href="{% url 'account_app:register' %}">Registrar</a>
                </div>
                {% endif %}
            </div>



        </div>

        {% block body_block %}
        <!-- Other Htmls go here -->
        {% endblock %}

    </body>
    <footer>
      <div class="ui inverted vertical footer segment shadow">
        <div class="ui center aligned container  shadow">
          <div class="ui stackable inverted divided grid">
            <div class="three wide column">
              <h4 class="ui inverted header ">Group 1</h4>
              <div class="ui inverted link list ">
                <a href="#" class="item">Link One</a>
                <a href="#" class="item">Link Two</a>
                <a href="#" class="item">Link Three</a>
                <a href="#" class="item">Link Four</a>
              </div>
            </div>
            <div class="three wide column">
              <h4 class="ui inverted header ">Group 2</h4>
              <div class="ui inverted link list ">
                <a href="#" class="item">Link One</a>
                <a href="#" class="item">Link Two</a>
                <a href="#" class="item">Link Three</a>
                <a href="#" class="item">Link Four</a>
              </div>
            </div>
            <div class="three wide column">
              <h4 class="ui inverted header ">Group 3</h4>
              <div class="ui inverted link list ">
                <a href="#" class="item">Link One</a>
                <a href="#" class="item">Link Two</a>
                <a href="#" class="item">Link Three</a>
                <a href="#" class="item">Link Four</a>
              </div>
            </div>
            <div class="seven wide column">
              <h4 class="ui inverted header " >Footer Header</h4>
              <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
            </div>
          </div>
          <div class="ui inverted section divider "></div>
          <div class="ui horizontal inverted small divided link list ">
            <a class="item" href="#">Site Map</a>
            <a class="item" href="#">Contact Us</a>
            <a class="item" href="#">Terms and Conditions</a>
            <a class="item" href="#">Privacy Policy</a>
          </div>
        </div>
      </div>
    </footer>
    {% block js_block %}
    <!-- Other js go here -->
    {% endblock %}
</html>

nss/account_app/templates/account_app/create_project.html
{% extends "account_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
    <div class="container">
      <h1 class="content">Crea tu proyecto</h1><br><br>
      <form method="POST" enctype="multipart/form-data"class="ui form">
      {% csrf_token %}
      {{ form_rol.management_form }}

      <!--<div class="fieldWrapper">
           {{ form_pro.pro_creation_date.errors }}
           {{ form_pro.pro_creation_date.label_tag }}
           {{ form_pro.pro_creation_date }}
       </div>-->

      <h3>Información del proyetco</h3>

      <div class="col-2">
        {{ form_pro.pro_name.errors }}
        {{ form_pro.pro_name.label_tag }}
        {{ form_pro.pro_name }}

        {{ form_pro.pro_video.errors }}
        {{ form_pro.pro_video.label_tag }}
        {{ form_pro.pro_video }}

        {{ form_pro.pro_phrase.errors }}
        {{ form_pro.pro_phrase.label_tag }}
        {{ form_pro.pro_phrase }}

        {{ form_pro.pro_category.errors }}
        {{ form_pro.pro_category.label_tag }}
        {{ form_pro.pro_category }}

        {{ form_pro.pro_description.errors }}
        {{ form_pro.pro_description.label_tag }}
        {{ form_pro.pro_description }}

        {{ form_pro.pro_about_us.errors }}
        {{ form_pro.pro_about_us.label_tag }}
        {{ form_pro.pro_about_us }}

        {{ form_pro.pro_creation_date.errors }}
        {{ form_pro.pro_creation_date.label_tag }}
        {{ form_pro.pro_creation_date }}

        {{ form_pro.pro_location.errors }}
        {{ form_pro.pro_location.label_tag }}
        {{ form_pro.pro_location }}

        {{ form_pro.pro_img.errors }}
        {{ form_pro.pro_location.label_tag }}
        {{ form_pro.pro_location }}

        <br>
        <input type="file" name="pro_img" id="id_pro_img" accept="image/*" multiple="">

      </div>
      <h3>Información de los roles</h3>
      <div class="table">
        {% for form in form_rol %}
        <ul>
          <li>{{ form }}</li>
        </ul>
      {% endfor %}
      </div>
      <input type="hidden" name="cantidad" id="cantidad"value="">

        <input type="button" value="Add More" id="add_more">
        <input type="submit" class="positive ui button" value="Submit">
      <!--  <div class="fieldWrapper">
            {{ form.ProName.errors }}
            {{ form.ProName.label_tag }}
            {{ form.ProName }}
        </div>-->
        <!--<button class="ui black button">Agregar Rol</button><br><br>-->

      </form>
    </div>
{% endblock %}
{% block js_block %}
<!-- Other js go here -->
    <script type="text/javascript">
        var dateToday = new Date();
      $(function() {
        $('input[id="id_pro_creation_date"]').daterangepicker({
          singleDatePicker: true,
          showDropdowns: true,
          maxDate: dateToday,
          locale: {
             format: 'YYYY-MM-DD'
            }
        });
        $('input[class="datepicker"]').daterangepicker({
          singleDatePicker: true,
          showDropdowns: true,
          minDate: dateToday,
          locale: {
             format: 'YYYY-MM-DD'
            }
        });

        console.log("HOLAA")
      });

    </script>
    <script type='text/javascript'>
            co=1;
              $('#add_more').click(function() {
                console.log("HOLA")
            cloneMore('div.table:last', 'service');
          });
          function cloneMore(selector, type) {
              var newElement = $(selector).clone(true);
              var total = $('#id_' + type + '-TOTAL_FORMS').val();
              console.log("total "+total)
              newElement.find(':input').each(function() {
                  var name = $(this).attr('name').replace('-' + (co-1) + '-','-' + co+ '-');
                  var id = 'id_' + name;
                  console.log("id "+id)
                  $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
              });
              newElement.find('label').each(function() {
                  var newFor = $(this).attr('for').replace('-' + (co-1) + '-','-' + co + '-');
                  $(this).attr('for', newFor);
              });
              total=total+1;
              co=co+1;
              console.log("total "+total)
              console.log("co "+co)
              $('#id_' + type + '-TOTAL_FORMS').val(co);
              $(selector).after(newElement);
              $('input[class="datepicker"]').daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                locale: {
                   format: 'YYYY-MM-DD'
                  }
              });
              document.getElementById("cantidad").value = co;
              console.log("cant " +   document.getElementById("cantidad").value);
          }
        </script>


{% endblock %}

nss/account_app/templates/account_app/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block title %}Teem{% endblock %}
{% block body_block %}

<main role="main">
  <div class="ui four column doubling stackable grid container">
      {% for project in projects|dictsort:"id" reversed %}
          <div class="column">
            <div class="ui fluid teal card">
              <a class="image"href="{% url 'project_app:project' project.id project.pro_name|slugify %}">
                  {% if project.pro_img %}
                    <img src="{{project.pro_img.url}}">
                  {% else %}
                    <img src="https://semantic-ui.com/images/wireframe/image.png">
                  {% endif %}
                </a>
              <div class="content">
                <a class="header" href="{% url 'project_app:project' project.id project.pro_name|slugify %}">{{project.pro_name}} </a>
                <div class="meta">
                  <i class="tags icon"></i>
                        {{project.pro_category}}, {{project.pro_subcategory}}.
                </div>
                <div class="meta">
                  <i class="map marker alternate icon"></i>
                        {{project.pro_city}}, {{project.pro_state}}.
                </div>
                <div class="description">
                     <p>{{project.pro_description | truncatewords:50 |safe}} </p><a href="{% url 'project_app:project' project.id project.pro_name|slugify %}">Leer más</a>
                   </div>
              </div>
              <div class="extra content">
                <span class="right floated">
                  {{project.pro_creation_date}}
                </span>
                <span>

                  <a class="ui image label" href="{% url 'profiles_app:detail' project.pro_user.profile.user.username %}">
                  {%if project.pro_user.profile.avatar%}
                  <img class="ui avatar image" src="{{project.pro_user.profile.avatar.url}}">
                  {{project.pro_user}}
                  {%else%}
                  <img class="ui avatar image" src="https://semantic-ui.com/images/avatar2/small/lena.png">
                  {{request.user.profile.user}}
                  {%endif%}
                  </a>

                     <div class="row mt-3">
                       <div class="col-md-9 mx-auto">
                         <div class="description">

                           {% if request.user == project.pro_user %}
                                 <a href="{% url 'project_app:applications' project.id %}">Ver solicitudes</a>
                               | <a href="{% url 'project_app:update' project.id %}">Editar</a>
                               | <a href="{% url 'project_app:delete' project.id %}">Borrar</a>
                             {% endif %}

                             <script type="text/javascript">
                             console.log("{% url 'project_app:project' project.id project.pro_name|slugify %}");

                             </script>

                         </div>
                       </div>
                     </div>
                   </span>
              </div>
            </div>
          </div>
      {% endfor %}
  </div>
</main>
{% endblock %}